blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='list_blog'),
    path('create/', BlogCreateView.as_view(), name='create_blog'),
    path('view/<slug:slug>/', BlogDetailView.as_view(), name='view_blog'),
    path('edit/<slug:slug>/', BlogUpdateView.as_view(), name='edit_blog'),
    path('delete/<slug:slug>/', BlogDeleteView.as_view(), name='delete_blog'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailings')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path
from mailings.apps import MailingsConfig
from mailings.views import MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView, \
    ClientCreateView, ClientListView, ClientDeleteView, home, mailing_toggle_activity

app_name = MailingsConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('list_mailing', MailingListView.as_view(), name='list_mailing'),
    path('view_mailing/<int:pk>/', MailingDetailView.as_view(), name='view_mailing'),
    path('create_mailing/', MailingCreateView.as_view(), name='create_mailing'),
    path('edit_mailing/<int:pk>/', MailingUpdateView.as_view(), name='edit_mailing'),
    path('delete_mailing/<int:pk>/', MailingDeleteView.as_view(), name='delete_mailing'),
    path('create_client/', ClientCreateView.as_view(), name='create_client'),
    path('list_client/', ClientListView.as_view(), name='list_client'),
    path('delete_client/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),
    path('mailing_activity/<int:pk>/', mailing_toggle_activity, name='mailing_toggle_activity'),
]

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='заголовок')
    slug = models.CharField(max_length=100, verbose_name='slug')
    content = models.TextField(verbose_name='содержимое статьи')
    image = models.ImageField(upload_to='blog/', null=True, blank=True, verbose_name='изображение')
    date_of_publication = models.DateTimeField(auto_now=False, auto_now_add=True, verbose_name='дата публикации')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f'{self.title} {self.date_of_publication}'

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'
        ordering = ('-date_of_publication',)

mailings/models.py
from django.conf import settings
from django.db import models


class Client(models.Model):
    email = models.EmailField(max_length=150, verbose_name='почта')
    full_name = models.CharField(max_length=150, verbose_name='ФИО')
    comment = models.TextField(verbose_name='комментарий',  null=True, blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='владелец', null=True)

    def __str__(self):
        return f'{self.full_name} - {self.email}'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'
        

class Mailing(models.Model):
    PERIOD_DAILY = 'daily'
    PERIOD_WEEKLY = 'weekly'
    PERIOD_MONTHLY = 'monthly'
    PERIODS = (
        (PERIOD_DAILY, 'Ежедневная'),
        (PERIOD_WEEKLY, 'Раз в неделю'),
        (PERIOD_MONTHLY, 'Раз в месяц'),
    )

    STATUS_CREATED = 'created'
    STATUS_STARTED = 'started'
    STATUS_DONE = 'done'
    STATUSES = (
        (STATUS_STARTED, 'Запущена'),
        (STATUS_CREATED, 'Создана'),
        (STATUS_DONE, 'Завершена'),
    )

    start_time = models.TimeField(verbose_name='время начала рассылки')
    end_time = models.TimeField(verbose_name='время окончания рассылки')
    period = models.CharField(max_length=20, choices=PERIODS, verbose_name='периодичность рассылки')
    status = models.CharField(max_length=20, choices=STATUSES, default='created', verbose_name='статус рассылки')
    client = models.ManyToManyField('Client', verbose_name='клиент', related_name='client')
    title_message = models.CharField(max_length=150, verbose_name='тема письма')
    body_message = models.TextField(verbose_name='тело письма')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='владелец', null=True)

    def __str__(self):
        return f'{self.start_time} - {self.end_time} ({self.period})'

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'
        ordering = ('start_time',)


class Log(models.Model):
    STATUS_OK = 'ok'
    STATUS_FAILED = 'failed'
    STATUSES = (
        (STATUS_OK, 'Успешно'),
        (STATUS_FAILED, 'Ошибка'),
    )

    datetime = models.DateTimeField(verbose_name='дата и время последней попытки')
    status = models.CharField(max_length=20, choices=STATUSES, verbose_name='статус')
    client = models.ForeignKey('Client', on_delete=models.CASCADE, verbose_name='клиент')
    mailing = models.ForeignKey('Mailing', on_delete=models.CASCADE, verbose_name='рассылка')
    error_msg = models.CharField(max_length=150,  null=True, blank=True, verbose_name='ответ почтового сервера')

    def __str__(self):
        return f'{self.datetime} - {self.status}'

    class Meta:
        verbose_name = 'лог'
        verbose_name_plural = 'логи'

mailings/forms.py
from django import forms

from mailings.models import Mailing, Client


class MailingForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Mailing
        fields = ('start_time', 'end_time', 'period', 'client', 'title_message', 'body_message')


class ClientForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Client
        fields = '__all__'

mailings/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.decorators.cache import cache_page
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from blog.models import Blog
from mailings.forms import MailingForm, ClientForm
from mailings.models import Mailing, Client


@cache_page(60)
def home(request):
    blog_list = Blog.objects.all()[:3]
    mailings_all = Mailing.objects.count()
    mailings_started = Mailing.objects.filter(status='started').count()
    client_all = Client.objects.distinct().count()
    context = {
        'blog_list': blog_list,
        'mailings_all': mailings_all,
        'mailings_started': mailings_started,
        'client_all': client_all,
    }

    return render(request, 'mailings/home.html', context)


class MailingListView(ListView):
    model = Mailing


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailings:home')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save
        return super().form_valid(form)


class MailingDetailView(DetailView):
    model = Mailing


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm

    def get_success_url(self):
        return reverse('mailings:view_mailing', args=[self.object.pk])

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save
        return super().form_valid(form)


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailings:home')


class ClientCreateView(CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailings:create_mailing')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save
        return super().form_valid(form)


class ClientListView(ListView):
    model = Client


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailings:list_client')


def mailing_toggle_activity(request, pk):
    mailing_item = get_object_or_404(Mailing, pk=pk)
    if mailing_item.status != 'done':
        mailing_item.status = 'done'
    else:
        mailing_item.status = 'started'

    mailing_item.save()

    return redirect(reverse('mailings:list_mailing'))

mailings/templates/mailings/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mailings: {{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>

{% include 'mailings/includes/inc_main_menu.html' %}

{% block content %}
{% endblock %}

<div class="container">
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Mailings
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

mailings/templates/mailings/client_confirm_delete.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6 text-center">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Удалить данного клиента?</p>
                    <button type="submit" class="p-2 btn btn-outline-danger">Подтвердить</button>
                    <a href="{% url 'mailings:view_mailing' object.pk %}" class="p-2 btn btn-outline-success">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/client_form.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="p-2 btn btn-outline-success">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Добавить
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/client_list.html
{% extends 'mailings/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-8">Список клиентов</h1>
</div>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th scope="col">Почта</th>
            <th scope="col">ФИО</th>
            <th scope="col">Комментарий</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for object in object_list %}
            {% if user.is_superuser or user == object.owner %}
                <tr>
                    <td scope="row">{{ object.email }}</td>
                    <td>{{ object.full_name }}</td>
                    <td>{{ object.comment }}</td>
                    <td>
                        <a class="p-2 btn btn-outline-danger" href="{% url 'mailings:delete_client' object.pk %}">Удалить клиента</a>
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
    </tbody>
</table>

<div class="d-grid gap-2 col-6 mx-auto">
    {% if user.is_authenticated %}
    <a class="p-2 btn btn-outline-success" href="{% url 'mailings:create_client' %}">Добавить нового клиента</a>
    {% endif %}
</div>
{% endblock %}

mailings/templates/mailings/home.html
{% extends 'mailings/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col">
            <div class="badge bg-primary text-wrap fs-6" style="width: 11rem;">
                Всего рассылок <span class="badge bg-secondary">{{ mailings_all }}</span>
            </div>
        </div>
        <div class="col">
            <div class="badge bg-primary text-wrap fs-6" style="width: 13rem;">
                Активных рассылок <span class="badge bg-secondary">{{ mailings_started }}</span>
            </div>
        </div>
        <div class="col">
            <div class="badge bg-primary text-wrap fs-6" style="width: 11rem;">
                Всего клиентов <span class="badge bg-secondary">{{ client_all }}</span>
            </div>
        </div>
    </div>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сервис рассылок</h1>
    {% if not user.is_authenticated %}
    <p class="lead">Для работы с рассылками зарегистрируйтесь или войдите</p>
    {% endif %}
</div>

<div class="container">
    <div class="row text-center">
        {% for blog in blog_list %}
            <div class="col-4">
                <div class="card mb-3">
                    <div class="row g-0">
                        <img src="{{ blog.image|mediapath }}" class="img-fluid rounded-start" alt="...">
                        <h5 class="card-title">
                            <a href = "{% url 'blog:view_blog' blog.slug %}">{{ blog.title|capfirst }}</a>
                        </h5>
                        <p class="card-text">
                            {% autoescape off %}
                                {{ blog.content|truncatechars:210 }}
                            {% endautoescape %}
                        </p>
                        <p class="card-text">
                            <small class="text-body-secondary">
                                Дата публикации {{ blog.date_of_publication }}<br>
                                Количество просмотров {{ blog.views_count }}
                            </small>
                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

mailings/templates/mailings/mailing_confirm_delete.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6 text-center">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Удалить данную рассылку?</p>
                    <button type="submit" class="p-2 btn btn-outline-danger">Подтвердить</button>
                    <a href="{% url 'mailings:view_mailing' object.pk %}" class="p-2 btn btn-outline-success">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/mailing_detail.html
{% extends 'mailings/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-5 px-5">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title text-center">
                            Детальная информация о рассылке
                        </h3>
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <tr>
                                <td>Время начала рассылки:</td>
                                <td>{{ object.start_time }}</td>
                            </tr>
                            <tr>
                                <td>Время окончания рассылки:</td>
                                <td>{{ object.end_time }}</td>
                            </tr>
                            <tr>
                                <td>Периодичность рассылки:</td>
                                <td>
                                    {% if object.period == 'daily' %}
                                    Ежедневная
                                    {% elif object.period == 'weekly' %}
                                    Раз в неделю
                                    {% else %}
                                    Раз в месяц
                                    {% endif %}
                                </td>
                            </tr>
                            <tr>
                                <td>Статус рассылки:</td>
                                <td>
                                    {% if object.status == 'created' %}
                                    Запущена
                                    {% elif object.status == 'started' %}
                                    Создана
                                    {% else %}
                                    Завершена
                                    {% endif %}
                                </td>
                            </tr>
                            <tr>
                                <td>Клиенты:</td>
                                <td>
                                    {% for client in object.client.all %}
                                    {{ client.email }}<br>
                                    {% endfor %}
                                </td>
                            </tr>
                            <tr>
                                <td>Тема письма:</td>
                                <td>{{ object.title_message }}</td>
                            </tr>
                            <tr>
                                <td>Тело письма:</td>
                                <td>{{ object.body_message }}</td>
                            </tr>
                        </table>
                    </div>
                    <div class="card-footer">
                        Автор: {{ object.owner }}<br>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="py-4 text-center">
        <a class="p-2 btn btn-outline-success" href="{% url 'mailings:edit_mailing' object.pk %}">Редактировать рассылку</a>
        <a class="p-2 btn btn-outline-danger" href="{% url 'mailings:delete_mailing' object.pk %}">Удалить рассылку</a>
    </div>

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h3 class="display-8">Логи по данной рассылке</h3>
    </div>

    <table class="table table-striped table-hover">
    <thead>
        <tr>
            <th scope="col">Дата и время последней попытки</th>
            <th scope="col">Статус</th>
            <th scope="col">Клиент</th>
            <th scope="col">Рассылка</th>
            <th scope="col">Ответ почтового сервера</th>
        </tr>
    </thead>
    <tbody>
        {% for log in object.log_set.all %}
            <tr>
                <td scope="row">{{ log.datetime }}</td>
                <td>{{ log.status }}</td>
                <td>{{ log.client.email }}</td>
                <td>{{ log.mailing }}</td>
                <td>{{ log.error_msg }}</td>
            </tr>
        {% endfor %}
    </tbody>
    </table>
{% endblock %}

mailings/templates/mailings/mailing_form.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="p-2 btn btn-outline-success">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Добавить
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/mailing_list.html
{% extends 'mailings/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-8">Список рассылок</h1>
</div>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th scope="col">Время начала рассылки</th>
            <th scope="col">Время окончания рассылки</th>
            <th scope="col">Периодичность рассылки</th>
            <th scope="col">Статус рассылки</th>
            <th scope="col">
                {% if user.is_authenticated and not user.is_staff %}
                Клиенты
                {% endif %}
                {% if user.is_superuser or user.is_staff %}
                Пользователь
                {% endif %}
            </th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for object in object_list %}
        {% if user.is_staff or user == object.owner %}
            <tr>
                <td scope="row">{{ object.start_time }}</td>
                <td>{{ object.end_time }}</td>
                <td>
                    {% if object.period == 'daily' %}
                    Ежедневная
                    {% elif object.period == 'weekly' %}
                    Раз в неделю
                    {% else %}
                    Раз в месяц
                    {% endif %}
                </td>
                <td>
                    {% if object.status == 'created' %}
                    Создана
                    {% elif object.status == 'started' %}
                    Запущена
                    {% else %}
                    Завершена
                    {% endif %}
                </td>
                <td>
                    {% if user.is_authenticated and not user.is_staff %}
                    {% for client in object.client.all %}
                        {{ client.email }}<br>
                    {% endfor %}
                    {% endif %}
                    {% if user.is_superuser or user.is_staff %}
                        {{ object.owner }}
                    {% endif %}
                </td>
                <td>
                    {% if user.is_authenticated and not user.is_staff %}
                        <a class="p-2 btn btn-outline-success" href="{% url 'mailings:view_mailing' object.pk %}">Детали</a>
                    {% endif %}
                    {% if user.is_superuser or user.is_staff %}
                    {% if object.status != 'done' %}
                        <a class="p-2 btn btn-outline-danger"
                           href="{% url 'mailings:mailing_toggle_activity' object.pk %}">Отключить рассылку
                        </a>
                    {% else %}
                        <a class="p-2 btn btn-outline-success"
                           href="{% url 'mailings:mailing_toggle_activity' object.pk %}">Включить рассылку
                        </a>
                    {% endif %}
                    {% endif %}
                </td>
            </tr>
        {% endif %}
        {% endfor %}
    </tbody>
</table>

<div class="d-grid gap-2 col-6 mx-auto">
    {% if user.is_authenticated and not user.is_staff %}
    <a class="p-2 btn btn-outline-success" href="{% url 'mailings:create_mailing' %}">Добавить новую рассылку</a>
    {% endif %}
</div>
{% endblock %}