blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='list_blog'),
    path('create/', BlogCreateView.as_view(), name='create_blog'),
    path('view/<slug:slug>/', BlogDetailView.as_view(), name='view_blog'),
    path('edit/<slug:slug>/', BlogUpdateView.as_view(), name='edit_blog'),
    path('delete/<slug:slug>/', BlogDeleteView.as_view(), name='delete_blog'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailings')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='заголовок')
    slug = models.CharField(max_length=100, verbose_name='slug')
    content = models.TextField(verbose_name='содержимое статьи')
    image = models.ImageField(upload_to='blog/', null=True, blank=True, verbose_name='изображение')
    date_of_publication = models.DateTimeField(auto_now=False, auto_now_add=True, verbose_name='дата публикации')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f'{self.title} {self.date_of_publication}'

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'
        ordering = ('-date_of_publication',)

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Blog


class BlogCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Blog
    fields = ('title', 'content', 'image', 'is_published')
    permission_required = 'blog.view_blog'
    success_url = reverse_lazy('blog:list_blog')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog
    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Blog
    fields = ('title', 'content', 'image', 'is_published')
    permission_required = 'blog.change_blog'

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        from django.urls import reverse
        return reverse('blog:view_blog', args=[self.object.slug])


class BlogDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Blog
    permission_required = 'blog.delete_blog'
    success_url = reverse_lazy('blog:list_blog')

blog/templates/blog/blog_confirm_delete.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6 text-center">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Удалить статью "{{ object.title }}"?</p>
                    <button type="submit" class="p-2 btn btn-outline-danger">Подтвердить</button>
                    <a href="{% url 'blog:list_blog' %}" class="p-2 btn btn-outline-success">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'mailings/base.html' %}

{% block content %}
    <h3 class="text-center">{{ object.title|capfirst }}</h3>
    <div class="text-center px-5">
        <img style="max-width: 540px;" src="/media/{{ object.image }}" />
    </div>
    {% autoescape off %}
        {{ object.content }}
    {% endautoescape %}
    <p></p>
    <p class="px-2">Дата создания: {{ object.date_of_publication }}</p>
    <p class="px-2">Количество просмотров: {{object.views_count }}</p>
    {% if user.is_staff %}
    <div class="py-4 text-center">
        <a class="p-2 btn btn-outline-success" href="{% url 'blog:edit_blog' object.slug %}">Редактировать статью</a>
        <a class="p-2 btn btn-outline-danger" href="{% url 'blog:delete_blog' object.slug %}">Удалить статью</a>
    </div>
    {% endif %}
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="p-2 btn btn-outline-success">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Добавить
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'mailings/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-8">Блог</h1>
</div>

<div class="container">
    {% for object in object_list %}
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="{{ object.image|mediapath }}" class="img-fluid rounded-start" alt="...">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title px-5">
                            <a href = "{% url 'blog:view_blog' object.slug %}">{{ object.title|capfirst }}</a>
                        </h5>
                        <p class="card-text">
                            {% autoescape off %}
                                {{ object.content|truncatechars:210 }}
                            {% endautoescape %}
                        </p>
                        <p class="card-text">
                            <small class="text-body-secondary">Дата создания: {{ object.date_of_publication }}|</small>
                            <small class="text-body-secondary">|Количество просмотров: {{ object.views_count }}</small>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% if user.is_staff %}
<div class="d-grid gap-2 col-6 mx-auto">
    <a class="p-2 btn btn-outline-success" href="{% url 'blog:create_blog' %}">Добавить новую статью</a>
</div>
{% endif %}
{% endblock %}