blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='list_blog'),
    path('create/', BlogCreateView.as_view(), name='create_blog'),
    path('view/<slug:slug>/', BlogDetailView.as_view(), name='view_blog'),
    path('edit/<slug:slug>/', BlogUpdateView.as_view(), name='edit_blog'),
    path('delete/<slug:slug>/', BlogDeleteView.as_view(), name='delete_blog'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailings')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, mail_verification, password_recovery, UserListView, user_toggle_activity

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('verification/<str:verification_code>/', mail_verification, name='verification'),
    path('recovery/', password_recovery, name='recovery'),
    path('list_user/', UserListView.as_view(), name='list_user'),
    path('user_activity/<int:pk>/', user_toggle_activity, name='user_toggle_activity'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    country = models.CharField(max_length=35, verbose_name='страна', **NULLABLE)
    verification_code = models.CharField(max_length=35, verbose_name='код верификации', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        ordering = ('email',)

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from users.models import User


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView
import random
from string import ascii_letters, digits

from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        if form.is_valid():
            password = ""
            for i in range(8):
                password += random.choice(list(ascii_letters + digits))
            new_user = form.save()
            new_user.verification_code = password
            new_user.is_active = False
            send_mail(
                'Подтвердите',
                f'Для подтверждения почты пройдите по ссылке http://127.0.0.1:8000/users/verification/{password}',
                settings.EMAIL_HOST_USER,
                [new_user.email]
            )
        return super().form_valid(form)


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


def mail_verification(verification_code):
    user = User.objects.get(verification_code=verification_code)
    if user is not None:
        user.is_active = True
        user.save()
    return redirect('users:login')


def password_recovery(request):
    if request.method == 'POST':
        new_password = ""
        for i in range(8):
            new_password += random.choice(list(ascii_letters + digits))
        email = request.POST.get('email')
        send_mail(
            'Новый пароль',
            f'Ваш новый пароль: {new_password}',
            settings.EMAIL_HOST_USER,
            [email]
        )
        user = User.objects.get(email=email)
        if user is not None:
            user.set_password(new_password)
            user.save()
    return render(request, 'users/recovery.html')


class UserListView(ListView):
    model = User


def user_toggle_activity(request, pk):
    user_item = get_object_or_404(User, pk=pk)
    if user_item.is_active:
        user_item.is_active = False
    else:
        user_item.is_active = True

    user_item.save()

    return redirect(reverse('users:list_user'))

users/templates/users/login.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Вход
                </h3>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <p>
                        <a href="{% url 'users:recovery' %}">Восстановить пароль</a>
                    </p>
                    <button type="submit" class="p-2 btn btn-outline-success">Войти</button>
                </form>
                <a></a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/recovery.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Восстановление пароля</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="email">Введите адрес электронной почты для восстановления пароля</label>
                        <input
                                type="text"
                                name="email"
                                class="form-control"
                                id="email"
                                placeholder="Почта" required>
                    </div>
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Подтвердить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Регистрация
                </h3>
            </div>
            <div class="card-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="p-2 btn btn-outline-success">Регистрация</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Профиль
                </h3>
            </div>
            <div class="card-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="p-2 btn btn-outline-success">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'mailings/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-8">Список пользователей</h1>
</div>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th scope="col">Почта</th>
            <th scope="col">Телефон</th>
            <th scope="col">Страна</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
    {% if user.is_superuser or user.is_staff %}
        {% for object in object_list %}
            {% if not object.is_superuser and not object.is_staff %}
                <tr>
                    <td scope="row">{{ object.email }}</td>
                    <td>{{ object.phone }}</td>
                    <td>{{ object.country }}</td>
                    <td>
                        {% if object.is_active %}
                        <a class="p-2 btn btn-outline-danger"
                           href="{% url 'users:user_toggle_activity' object.pk %}">Заблокировать пользователя
                        </a>
                        {% else %}
                        <a class="p-2 btn btn-outline-success"
                           href="{% url 'users:user_toggle_activity' object.pk %}">Разблокировать пользователя
                        </a>
                        {% endif %}
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
    {% endif %}
    </tbody>
</table>

{% endblock %}

users/templates/users/verification.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Проверка почты
                </h3>
            </div>
            <div class="card-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="p-2 btn btn-outline-success">Код подтверждения</button>
                </form>
                <a></a>
            </div>
        </div>
    </div>
</div>
{% endblock %}